# Generated by Django 4.2 on 2023-04-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
