# Generated by Django 4.2 on 2023-04-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
