# Generated by Django 4.2 on 2023-04-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_user_locations'),
        ('ads', '0004_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='Локация'),
        ),
    ]
